name: Ultroid

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "Var.HNDLR"

          replace: "HNDLR"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Aa Muh me le le '
          
          commit_options: '--no-verify'

          repository: .

          commit_user_name: ProgrammingError

          commit_user_email: error@notavailable.live
